---
- name: Deploy app in new namespace
  # must be localhost, as we connect to the cluster from localhost
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        # instead of setting it here, set K8S_AUTH_KUBECONFIG environment variable
        # kubeconfig: /home/mueller/kubeconfig_myapp-eks-cluster
    - name: Deploy nginx app 
      kubernetes.core.k8s:
        src: nginx-config.yaml
        state: present
        # state = absent with the same file would remove the resources
        # state: present
        namespace: my-app
        # instead of setting it here, set K8S_AUTH_KUBECONFIG environment variable
        # kubeconfig: /home/mueller/kubeconfig_myapp-eks-cluster
