- name: Copy docker compose
  copy:
    # file is used directly from the files folder of the role
    src: docker-compose.yaml
    dest: /home/mueller/docker-compose.yaml
- name: Docker login
  docker_login:
    registry_url: "{{docker_registry}}"
    username: "{{docker_username}}"
    password: "{{docker_password}}"
- name: Start containers from compose
  community.docker.docker_compose_v2:
    project_src: /home/mueller